# Generated by Django 5.1.3 on 2024-11-17 16:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephotos',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersphoto',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
