# Generated by Django 5.1.3 on 2024-11-17 17:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_recipephotos_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipephotos',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo URL'),
        ),
        migrations.AlterField(
            model_name='usersphoto',
            name='photo_url',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo URL'),
        ),
    ]
