# Generated by Django 5.1.3 on 2024-12-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_recipephotos_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipephotos',
            options={'verbose_name': 'Recipe Photo', 'verbose_name_plural': 'Recipes Photos'},
        ),
        migrations.AlterModelOptions(
            name='usersphoto',
            options={'verbose_name': 'User Photo', 'verbose_name_plural': 'User Photos'},
        ),
    ]
