# Generated by Django 5.1.3 on 2024-12-10 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['category_name'], name='categories__categor_2f14bf_idx'),
        ),
    ]
