# Generated by Django 5.1.3 on 2024-11-16 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_difficulty_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=1, validators=[django.core.validators.MinValueValidator(50)]),
            preserve_default=False,
        ),
    ]
