# Generated by Django 5.1.3 on 2024-11-16 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
